[[authentication-use-cases]]
== Authentication Use Cases

[[authentication-use-cases-backend-services]]
=== Backend Service Integration

You may want to use Boclips straight from your backend services. In this case the OAuth 2 flow to use should will be `client_credentials` and Boclips will provide
you with your own `client_id` and `client_secret`.

All the communication will happen outside of the context of a user in that case, therefore some features like user collections
may not be available (See <<user-context>> if user based features are needed).

In order to get an access token using `client_credentials` we would perform a request:

operation::client-credentials-example[snippets='http-request,curl-request,request-parameters']

Assuming all the parameters are correct, you will get a <<authentication-token-response,valid token response>> back.

[[overriding-user-id]]
==== Providing a user identifier for analytics
If you're planning to use our user based API features, we recommend using <<user-context>> instead.

As mentioned above, backend service integrations happen without the end-user context, but for analytics and billing purposes it may be required to provide an id that will uniquely identify users (even if their true identities remain anonymous to Boclips).

To achieve this, you can manually add a user id to any requests you send to us by including a header:

----
Boclips-User-Id: [your user id]
----

[[user-context]]
==== Full user context
CAUTION: This feature is still in beta and could potentially change.

Typically the `client_credentials` flow does not contain a user context due to its machine to machine nature.
However, Boclips offers a way for integrations to give this context, which will enable the use of features such as individual user's collections.
This works by generating a unique access token for each user.
To achieve this, you can manually add a user id when requesting a token via the <<authentication-use-cases-backend-services, client_credentials flow>> by including a header:

----
Boclips-User-Id: [your user id]
----
[IMPORTANT]
====
[your user id] length must be no longer than 64 characters.
====

That will provide you with access token personalised for the user identified by header. It means you can use this token for all requests that need this user's context, without any additional headers.

When accessing the API on behalf of another user, you must generate a new token for that user. The user id passed to us must be unique across all of your users.

[[authentication-use-cases-sso]]
=== Using your platform as SSO

You may want to integrate your existing user base with Boclips. If you authenticate your users via an OpenID Connect identity provider (IdP), Boclips API will provide a seamless SSO experience.

Any authenticated user coming from your system will be able to execute calls against Boclips API without having to go through any additional authentication/authorization steps, as Boclips' IdP will query your IdP behind the scenes to verify user identity.

==== Configuring Identity Federation

This mechanism of different IdPs talking to each other to authenticate users is called _identity federation_. Setting it up is a matter providing your IdP's configuration to Boclips authentication server.

Luckily, this information is provided in a well known format that can be easily retrieved and processed by us.

===== OIDC

OIDC IdPs by convention expose their configuration via a `.well-known/openid-configuration` endpoint, this mechanism is called OpenID Connect Discovery.

https://api.boclips.com/v1/.well-known/openid-configuration[Here] you can see how this information looks like for Boclips.

==== Configuring an OIDC Client

The second configuration step is OIDC client information. We need a list of https://www.oauth.com/oauth2-servers/redirect-uris/[redirect URIs] to know where your users can be securely redirected to after we confirm their identity.

After the client is registered on our side we can share a `client_id` with you.

[[authentication-use-cases-authorization-code-grant]]
==== Retrieving an Access Token

Once setup is done and access credentials have been exchanged with you, you'll need to perform an https://oauth.net/2/grant-types/authorization-code/[authorization code] grant flow
to retrieve a Boclips API access token.

This authentication flow works slightly differently depending on whether your application is a https://www.oauth.com/oauth2-servers/server-side-apps/[server-side application], or a https://www.oauth.com/oauth2-servers/single-page-apps/[single-page application]. Either way, it works roughly as outlined below:

. The user's browser visits your application. The application notices the user is not logged in, so it <<trigger-authorization,redirects the browser to our server>> to be authenticated. The application passes along a callback URL (a redirect URL)  as a query parameter in this browser redirect that our server will use when it finishes authentication. Then:
.. if the user has a session in your domain — we'll move to the next point,
.. if the user has no session in your domain we'll send them to your login page (this needs to be configured on our end).

. Given your IdP acknowledges your user, our server authenticates the user and creates a one-time temporary code. Our server redirects back to the application using the callback URL provided earlier and additionally adds this temporary code as a query parameter in the callback URL.

. Your application extracts the temporary code and <<get-token-authorization,makes a background HTTP request>> to our authentication server to exchange the code for an identity, access and refresh token. Once this temporary code has been used to obtain the tokens, it can never be used again. This prevents potential replay attacks.

[[authentication-use-cases-mobile-apps]]
=== Authenticating mobile applications

Authenticating mobile applications is possible with both options described above.

When working with a <<authentication-use-cases-backend-services,backend service integration>>, your mobile app will simply be calling your backend services which, having access to client secret, will handle authentication themselves.

In the case of an <<authentication-use-cases-sso,SSO integration>>, mobile apps can't guarantee the confidentiality of a client secret and therefore will be using a public client. That implies a <<authentication-use-cases-authorization-code-grant,flow>> analogous to the one web applications go through, with some additional security considerations.

We recommend going through this https://www.oauth.com/oauth2-servers/mobile-and-native-apps/[official guide] on developing mobile apps authentication with OAuth 2.

==== Mobile browser usage

The nature of authenticating using a public OAuth client implies the user will have to visit IdP server's login/authorization page. Mobile apps give you the option of displaying that page either in a custom embedded view, or using a mobile platform's native browser.

The official security recommendation is to always use the native browser. This allows the user to verify that the page they're visiting is valid and they will also benefit from shared system cookies.

==== Proof for Key Code Exchange

If your IdP supports https://www.oauth.com/oauth2-servers/pkce/[PKCE], it's worth using it to benefit from an additional layer of security. PKCE protects users from authentication traffic interception attacks.
