[[resources-collections]]
== Collections

Collections enable grouping related videos together and have some additional metadata that describes their content. They are searchable, can be edited and bookmarked.

Each collection can be *public* or *private*. A public collection will be visible to all authenticated users through the search capability. Private collections will be visible only to their *owner*, i.e. user who created them.

[[resources-collections-create]]
=== Creating a collection

Collections can be created by issuing a `POST` request to `createCollection` link. Input parameters are provided via a JSON payload.

Upon success, the API will respond with a `201` status and provide a link to the newly created collection under a `Location` response header.

operation::resource-collection-creation[snippets='request-fields,http-request,curl-request,http-response']

[[resources-collections-retrieve]]
=== Retrieving a collection

You can retrieve collections by sending a `GET` request to `collection` link. It's a templated link with a collection `id` path parameter.

Alternatively you can of course use an absolute link to a specific collection that you have, e.g. when it's extracted from a `Location` header after <<resources-collections-create,creating>>.

operation::resource-collection[snippets='path-parameters,http-request,curl-request,http-response,response-fields,links']

==== Projections

The API supports two projections -- `list` and `details`. The former is used by default and returns shallow details of sub-resources. The other one will fetch sub-resources along. Projection can be specified via a query parameter:

operation::resource-collection-detailed[snippets='http-request,http-response']

[[resources-collections-search]]
=== Collection search

Boclips API allows searching through collections via `searchCollections` and `searchPublicCollections` links. Former will return results from among the collections the user created themself and the public collections, the latter will process through public ones only.

Note that the first search link allows to compose a query that searches for public collections as well, so the second one essentially serves as a convenient shorthand.

Collection search results are pageable -- you can control both the page number and page size.

operation::resource-collection-search[snippets='request-parameters,http-request,curl-request,http-response,response-fields,links']

[[resources-collections-edit]]
=== Editing collections

==== Updating selected fields

A collection can be edited by sending a `PATCH` request to its `edit` link. Input parameters are provided via a JSON payload. Example below shows all possible values, but subsets can be submitted as well.

Upon success, the API will respond with a `204` status.

operation::resource-collection-edit[snippets='request-fields,http-request,curl-request,http-response']

==== Adding videos to a collection

A video can be added to a collection by sending a `PUT` request to the `addVideo` link. It's a templated link with a `video_id` path parameter.

Upon success, the API will respond with a `204` status.

operation::resource-collection-add-video[snippets='path-parameters,http-request,curl-request,http-response']

==== Removing videos from a collection

A video can be removed from a collection by sending a `DELETE` request to the `removeVideo` link. It's a templated link with a `video_id` path parameter.

Upon success, the API will respond with a `204` status.

operation::resource-collection-remove-video[snippets='path-parameters,http-request,curl-request,http-response']
