[[resources-collections]]
== Collections

Collections enable grouping related videos together and have some additional metadata that describes their content. They are searchable, can be edited and bookmarked.

[[resources-collections-create]]
=== Creating a collection

Collections can be created by issuing a `POST` request to <<resources-index-access_links,`createCollection`>> link. Input parameters are provided via a JSON payload.

Upon success, the API will respond with a `201` status and provide a link to the newly created collection under a `Location` response header.

operation::resource-collection-creation[snippets='request-fields,http-request,curl-request,http-response']

[[resources-collections-retrieve]]
=== Retrieving a collection

You can retrieve collections by sending a `GET` request to <<resources-index-access_links,`collection`>> link. It's a templated link with a collection `id` path parameter.

Alternatively you can of course use an absolute link to a specific collection that you have, e.g. when it's extracted from a `Location` header after <<resources-collections-create,creating>>.

operation::resource-collection[snippets='path-parameters,http-request,curl-request,http-response,response-fields,links']

[[resources-collections-attachments]]
==== Attachments

Attachments allow linking additional resources to video collections. The only type of attachments currently supported are lesson plans, which are in form of a hyperlink to an external document that can be accessed by collection's viewer. Additionally, an attachment can have a description.

operation::resource-collection[snippets='response-fields-attachments']

[[resources-collections-projections]]
==== Projections

The API supports two projections -- `list` and `details`. They are used to control how sub-resources will be returned from the collection API call:

- `list` will return only the id on returned video sub-resources.
- `details` will return all fields of video sub-resources.

Projection can be specified via a query parameter and defaults to `list`:

operation::resource-collection-detailed[snippets='http-request,http-response']

[[resources-collections-search]]
=== Collection search

Boclips API allows searching through collections via <<resources-index-access_links,`searchCollections`>>.


Collection search results are pageable -- you can control both the page number and page size.

You can filter collections by lesson plans. If you include `has_lesson_plans` flag in your query, you'll be given list of collection that will only have lesson plan attachments.

operation::resource-collection-search[snippets='request-parameters,http-request,curl-request,http-response,response-fields,links']

[[resources-collections-edit]]
=== Editing collections

==== Updating selected fields

A collection can be edited by sending a `PATCH` request to its `edit` link. Input parameters are provided via a JSON payload. You can update only specific fields of a given collection, you don't need to always submit full details.

Upon success, the API will respond with a `204` status.

Example below shows all possible values, but subsets can be submitted as well.

operation::resource-collection-edit[snippets='request-fields,request-fields-attachment,http-request,curl-request,http-response']

==== Adding videos to a collection

A video can be added to a collection by sending a `PUT` request to the `addVideo` link. It's a templated link with a `video_id` path parameter.

Upon success, the API will respond with a `204` status.

operation::resource-collection-add-video[snippets='path-parameters,http-request,curl-request,http-response']

==== Removing videos from a collection

A video can be removed from a collection by sending a `DELETE` request to the `removeVideo` link. It's a templated link with a `video_id` path parameter.

Upon success, the API will respond with a `204` status.

operation::resource-collection-remove-video[snippets='path-parameters,http-request,curl-request,http-response']

[[resources-collections-bookmark]]
=== Bookmarking collections

Collections you haven't created yourself can be bookmarked. This means that they will be returned from a query executed by following the <<resources-index-access_links,`bookmarkedCollections`>> link.

In order to bookmark a collection you should follow its `bookmark` link. Analogously, a `unbookmark` link will be available for collections that you've already bookmarked.

Upon successful (un)bookmarking, the API will respond with a 200 response and return the updated resource.

operation::resource-collection-bookmark[snippets='http-request,curl-request,http-response']
