[[resources-learning-outcomes-assessment-questions]]
== Learning Outcomes, Assessment Questions, and Highlights
CAUTION: These features are still in beta and could potentially change.

=== Retrieving learning outcomes
List of key takeaways for the video

[IMPORTANT]
====

*Data provided by this endpoint is AI-generated*

Read more about our AI policy https://www.boclips.com/ai-policy[here]
====

operation::learning-outcomes-get[snippets='path-parameters,http-request,curl-request,http-response']

=== Retrieving assessment questions
List of questions that could be asked about the content of the video in an assessment

[IMPORTANT]
====

*Data provided by this endpoint is AI-generated*

Read more about our AI policy https://www.boclips.com/ai-policy[here]
====

operation::assessment-questions-get[snippets='path-parameters,http-request,curl-request,http-response']

=== Retrieving filtered highlights
List of filtered highlights

[IMPORTANT]
====

*Data provided by this endpoint is AI-generated, in BETA, not subject to our SLA policies, and format may change with short notice.*

Read more about our AI policy https://www.boclips.com/ai-policy[here]
====

You can specify a version of this endpoint by passing the `X-Boclips-Api-Version` header in YYYY-MM-DD format.
 We strongly advise sending this to protect against breaking changes. The current version is 2024-04-24

----
"X-Boclips-Api-Version": "YYYY-MM-DD"
----

operation::highlights-get[snippets='request-parameters,http-request,curl-request,http-response']

=== Retrieving highlights
Retrieve a specific highlight by ID

[IMPORTANT]
====

*Data provided by this endpoint is AI-generated, in BETA, not subject to our SLA policies, and format may change with short notice.*

Read more about our AI policy https://www.boclips.com/ai-policy[here]
====

You can specify a version of this endpoint by passing the `X-Boclips-Api-Version` header in YYYY-MM-DD format.
 We strongly advise sending this to protect against breaking changes. The current version is 2024-04-24

----
"X-Boclips-Api-Version": "YYYY-MM-DD"
----

operation::highlight-get[snippets='path-parameters,http-request,curl-request,http-response']

