[[resources-learning-outcomes-assessment-questions]]
== Learning outcomes and assessment questions
CAUTION: These features are still in beta and could potentially change.

=== Retrieving learning outcomes
List of key takeaways for the video

[IMPORTANT]
====

*Data provided by this endpoint is AI-generated*

Read more about our AI policy https://www.boclips.com/ai-policy[here]
====

operation::learning-outcomes-get[snippets='path-parameters,http-request,curl-request,http-response']

=== Retrieving assessment questions
List of questions that could be asked about the content of the video in an assessment

[IMPORTANT]
====

*Data provided by this endpoint is AI-generated*

Read more about our AI policy https://www.boclips.com/ai-policy[here]
====

operation::assessment-questions-get[snippets='path-parameters,http-request,curl-request,http-response']

=== Retrieving filtered highlights
List of filtered highlights

[IMPORTANT]
====

*Data provided by this endpoint is AI-generated*

Read more about our AI policy https://www.boclips.com/ai-policy[here]
====

operation::highlights-get[snippets='path-parameters,http-request,curl-request,http-response']

=== Retrieving highlights
Retrieve a specific highlight by ID

[IMPORTANT]
====

*Data provided by this endpoint is AI-generated*

Read more about our AI policy https://www.boclips.com/ai-policy[here]
====

operation::highlight-get[snippets='path-parameters,http-request,curl-request,http-response']

