[[resources-videos]]
== Videos

The videos resource contains metadata about a Boclips video asset. This includes basic metadata as well as
streaming details.

[[resources-video-access]]
=== Accessing a single video

A `GET` request against the `video` link will return an individual video as long as its `id` is interpolated
following the provided template under <<resources-index-access,links>>.

operation::resource-video[snippets='path-parameters,http-request,curl-request,http-response,response-fields,response-fields-playback,links']


[[resources-video-search]]
=== Video search

A `GET` request against the `search` link will return a collection of videos.
Videos can be filtered using the criteria provided under the <<resources-index-access,templated `search` link>>.

If the API user has subjects associated with their account, i.e. "Mathematics", the search will be weighted to
prefer videos with those same subjects.

operation::resource-video-search[snippets='request-parameters,http-request,curl-request,http-response,response-fields']
