[[resources-videos]]
== Videos

The videos resource contains metadata about a Boclips video asset. This includes basic metadata as well as
streaming details.

[[resources-video-access]]
=== Accessing a single video

A `GET` request against the `video` link will return an individual video as long as its `id` is interpolated
following the provided template under <<resources-index-access,links>>.

operation::resource-video[snippets='path-parameters,http-request,curl-request,http-response,response-fields,response-fields-playback,links']

[[resources-video-search]]
=== Video search

A `GET` request against the `search` link will return a collection of videos.
Videos can be filtered using the criteria provided under the <<resources-index-access,templated `search` link>>.

If the API user has subjects associated with their account, i.e. "Mathematics", the search will be weighted to
prefer videos with those same subjects.

operation::resource-video-search[snippets='request-parameters,http-request,curl-request,http-response,response-fields']

[[resources-video-search-facets]]
==== Search facets

WARNING: This is a *_BETA_* feature. Whilst we don't anticipate major changes, we cannot guarantee backward compatibility at this stage.

Search facets expose hit counts for specific "buckets", namely *subjects*, *age ranges* and *durations*. Facets can substantially improve the search experience of users.

We provide default search facets out of the box. By setting the `age_range_facets` and `duration_facets` parameters, you can adapt the facets to meet your needs.

*Age Range Defaults* (in years): 3-5, 5-9, 9-11, 11-14, 14-16, 16-99

Age Range buckets will show the counts for videos which are suitable for at least 2 ages in that range.
For example a video which has `ageRange: {min: 4, max: 10}` would be counted in these buckets: 3-5, 5-9, 9-11.

*Durations Defaults* (in seconds): 0-120, 120-300, 300-600, 600-1200, 1200-86400

[[resources-video-types]]
=== Video types

Video types available in the system can be listed using the <<resources-index-access_links,`videoTypes`>> link.

operation::resource-video-types[snippets='http-request,curl-request,http-response,response-fields']
