[[resources-videos]]
== Videos

The videos resource contains metadata about a Boclips video asset. This includes basic metadata as well as
streaming details.

[[resources-video-access]]
=== Accessing a single video

A `GET` request against the `video` link will return an individual video as long as its `id` is interpolated
following the provided template under <<resources-index-access,links>>.

operation::resource-video[snippets='path-parameters,http-request,curl-request,http-response,response-fields,response-fields-playback,response-fields-contentWarnings,response-fields-bestFor,links']

[[resources-video-search]]
=== Video search

A `GET` request against the `search` link will return a collection of videos.
Videos can be filtered using the criteria provided under the <<resources-index-access,templated `search` link>>.

If the API user has subjects associated with their account, i.e. "Mathematics", the search will be weighted to
prefer videos with those same subjects.

operation::resource-video-search[snippets='request-parameters,http-request,curl-request,http-response,response-fields']

[[resources-video-search-age-ranges]]
==== Filtering by ages

We provide two ways of filtering videos by ages.

1. Using `age_range_min` and `age_range_max` you apply a *strict* filter. We return videos which are only suitable to ages `≥ age_range_min` and `≤ age_range_max`.

2. Using `age_range` you can apply a *relaxed* filter, where we return all videos which are suitable for at least 2 ages from the provided `age_range`.



|===
|Video age range | Search with filter: `age_range_min=3&age_range_max=5` | Search with filter: `age_range=3-5`

| 3 - 16
|no match, has age > max 5
|match

| 3-5
|match
|match

| 2 - 3
|no match, has age < min
|no match, only matches age 3, we need at least two matching ages

| 2 - 15
|no match, has age < min and age > max
|match

|===



[[resources-video-search-facets]]
==== Search facets

WARNING: This is a *_BETA_* feature. Whilst we don't anticipate major changes, we cannot guarantee backward compatibility at this stage.

Search facets expose hit counts for specific "buckets", namely *subjects*, *age ranges* and *durations*. Facets can substantially improve the search experience of users.

We provide default search facets out of the box. By setting the `age_range_facets` and `duration_facets` parameters, you can adapt the facets to meet your needs.

*Age Range Defaults* (in years): 3-5, 5-9, 9-11, 11-14, 14-16, 16-99

Age Range buckets will show the counts for videos which are suitable for at least 2 ages in that range.
For example a video which has `ageRange: {min: 4, max: 10}` would be counted in these buckets: 3-5, 5-9, 9-11.

*Durations Defaults* (in seconds): 0-120, 120-300, 300-600, 600-1200, 1200-86400

[[resources-video-types]]
=== Video types

Video types available in the system can be listed using the <<resources-index-access_links,`videoTypes`>> link.

operation::resource-video-types[snippets='http-request,curl-request,http-response,response-fields']

[[resources-video-feed]]
=== Video Feed
WARNING: This is a *_BETA_* feature. Whilst we don't anticipate major changes, we cannot guarantee backward compatibility at this stage.

Sometimes you may want to ingest all videos in the Boclips offering to enrich with your own metadata.
Currently, <<resources-video-search, `video search`>> is optimised for quick reads and limits the maximum window, so you can't request a page deeper than 10000 results.
A GET request to `videoFeed` will allow you to page through all the videos.

operation::resource-video-feed[snippets='request-parameters,http-request,curl-request,http-response,response-fields,links']

==== Caveats
- The maximum page size is 1000 results. Any larger will result in a 400 returned.
- We keep the context of the feed request alive for 5 minutes, which is reset after any request with the same `cursor_id`.
This means after a request you have 5 minutes to make another request to fetch the next page of results or the context will timeout and a 400 is returned
- The end of results is given by returning an empty list of videos and no `next` link is returned
- Making the request twice with the same `cursor_id` is essentially the same as following the next link

