#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
dir=$(mktemp -d -t fly-build-api-docs.XXXXX)
tidy () {
    rm -rf "$dir"
}

trap tidy EXIT

mkdir "$dir/version"
echo TEST_VERSION > "$dir/version/tag"

API_USERNAME="api@boclips.com"
API_PASSWORD="$(bo show credential concourse-main boclips.api-docs api-user-password)"
API_FRESHUSER_USERNAME="fresh@user.com"
API_FRESHUSER_PASSWORD="$(bo show credential concourse-main boclips.api-docs fresh-user-password)"
API_UPDATABLEUSER_USERNAME="updatable@user.com"
API_UPDATABLEUSER_PASSWORD="$(bo show credential concourse-main boclips.api-docs updatable-user-password)"
API_CLIENTID="api-docs"
API_CLIENTSECRET="$(bo show credential concourse-main keycloak-vars staging | jq .api_docs_client_secret)"
API_PRODUCTIONUSER_USERNAME="engineering+api-docs@boclips.com"
API_PRODUCTIONUSER_PASSWORD="$(bo show credential concourse-main boclips.api-docs production-user-password)"
LTI_V1P1_CONSUMERKEY="$(bo show credential concourse-main boclips.api-docs lti-v1p1-consumer-key)"
LTI_V1P1_CONSUMERSECRET="$(bo show credential concourse-main boclips.api-docs lti-v1p1-consumer-secret)"

export API_USERNAME
export API_PASSWORD
export API_FRESHUSER_USERNAME
export API_FRESHUSER_PASSWORD
export API_UPDATABLEUSER_USERNAME
export API_UPDATABLEUSER_PASSWORD
export API_CLIENTID
export API_CLIENTSECRET
export API_PRODUCTIONUSER_USERNAME
export API_PRODUCTIONUSER_PASSWORD
export LTI_V1P1_CONSUMERKEY
export LTI_V1P1_CONSUMERSECRET

fly --target ci \
    execute \
    --config "$cwd/pipeline/tasks/build.yml" \
    --input source="$cwd" \
    --input version="$dir/version" \
    --inputs-from=boclips/generate-api-docs
