#!/usr/bin/env bash

# This assumes you have provisioned the machine
ktlint --apply-to-idea-project

# Generate external contract test configuration
pushd src/test/resources/
./setup-contract-test
echo "set up contract tests"
popd
