---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-stretch

inputs:
  - name: source
  - name: version
  - name: player-source

outputs:
  - name: dist

params:
  API_USERNAME:
  API_PASSWORD:

  API_CLIENTID:
  API_CLIENTSECRET:
  LTI_V1P1_CONSUMERKEY:
  LTI_V1P1_CONSUMERSECRET:
  API_FRESHUSER_USERNAME:
  API_FRESHUSER_PASSWORD:
  API_UPDATABLEUSER_USERNAME:
  API_UPDATABLEUSER_PASSWORD:

caches:
  - path: .gradle/
  - path: source/dependency-check-cache

run:
  path: source/pipeline/scripts/build.sh
