= Boclips API Guide
Boclips Engineering;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response
:snippets: ../../../build/generated-snippets

[[overview]]
= Overview
This is the reference guide to the Boclips API.

[[overview-http-verbs]]
== HTTP verbs

The API adheres as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs. Supported operations vary from resource to resource.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PUT`
| Used to fully replace an existing resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview-http-status-codes]]
== HTTP status codes

The API adheres as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

[[overview-hypermedia]]
== Hypermedia

The API uses hypermedia, and resources include links to other resources in their
responses. Responses are in http://stateless.co/hal_specification.html[Hypertext Application
from resource to resource.
Language (HAL)] format. Links can be found beneath the `_links` key. *Users of the API should
not create URIs themselves*, but instead should use the above-described links to navigate.

[[overview-errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object
that describes the problem. The error object has the following structure:

include::{snippets}/error-example/response-fields.adoc[]

For example, a request that attempts to apply a non-existent tag to a note will produce a
`400 Bad Request` response:

include::{snippets}/error-example/http-response.adoc[]

[[errors-cors]]
=== Cross-Origin Resource Sharing

Any requests to our API originating from within a browser will be subject to CORs restrictions.

If you receive any CORs related errors it is possible the API requests have originated from a
domain that has not been whitelisted on our server.

Please contact us with any domains that you expect to call our API from (including protocols
and port numbers -- if necessary).

[[resources]]
= Resources

[[resources-index]]
== Index

The index provides the entry point into the service. Links can be pulled from here.

[[resources-index-access]]
=== Accessing the index

A `GET` request is used to access the index.

operation::resource-index[snippets='http-request,curl-request,http-response,links']

[[resources-video]]
== Video

The video resource contains metadata about a Boclips video asset. This includes basic metadata as well as
streaming details.

[[resources-video-access]]
=== Accessing a single video

A `GET` request against the `video` link will return an individual video as long as its `id` is interpolated
following the provided template under <<resources-index-access,links>>.

operation::resource-video[snippets='path-parameters,http-request,curl-request,http-response,response-fields,links']


[[resources-video-search]]
=== Video search

A `GET` request against the `search` link will return a collection of videos.
Videos can be filtered using the criteria provided under the <<resources-index-access,templated `search` link>>.

operation::resource-video-search[snippets='request-parameters,http-request,curl-request,http-response,response-fields']



