= Boclips API Guide
Boclips Engineering;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response
:snippets: ../../../build/generated-snippets

[[overview]]
= Overview
This is the reference guide to the Boclips API.

[[overview-http-verbs]]
== HTTP verbs

The API adheres as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs. Supported operations vary from resource to resource.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PUT`
| Used to fully replace an existing resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview-http-status-codes]]
== HTTP status codes

The API adheres as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

[[overview-hypermedia]]
== Hypermedia

The API uses hypermedia, and resources include links to other resources in their
responses. Responses are in http://stateless.co/hal_specification.html[Hypertext Application
from resource to resource.
Language (HAL)] format. Links can be found beneath the `_links` key. *Users of the API should
not create URIs themselves*, but instead should use the above-described links to navigate.

[[overview-errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object
that describes the problem. The error object has the following structure:

include::{snippets}/error-example/response-fields.adoc[]

For example, a request that attempts to apply a non-existent tag to a note will produce a
`400 Bad Request` response:

include::{snippets}/error-example/http-response.adoc[]

[[errors-cors]]
=== Cross-Origin Resource Sharing

Any requests to our API originating from within a browser will be subject to CORs restrictions.

If you receive any CORs related errors it is possible the API requests have originated from a
domain that has not been whitelisted on our server.

Please contact us with any domains that you expect to call our API from (including protocols
and port numbers -- if necessary).

[[overview-authentication]]
== Authentication

The Boclips API authorization is based on https://openid.net/connect/[OpenID Connect (OIDC)]. Alternatively,
we support https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language[SAML] too.

In order to get started with OIDC, we'll need to obtain an `access_token`. Depending on the type of integration,
we can provide different `grant_types`.

Boclips will provide you with a `client_id` and depending on the integration a `client_secret`.

Regardless of how the token is retrieved, the structure of the response will look like this:

[[token-response]]
include::{snippets}/refresh-token-example/response-body.adoc[]
include::{snippets}/refresh-token-example/response-fields.adoc[]


=== OIDC Use cases

==== Backend service integration

You may want to use Boclips straight from your backend services. In this case, Boclips will provide
you with your own `client_id` and `client_secret`.

All the communication will happen outside of the context of a user, therefore some features like user collections
may not be available.

In order to get an `access_token` using `client_credentials` we would perform a request:

operation::client-credentials-example[snippets='http-request,curl-request']


Assuming all the parameters are correct, you will get a <<token-response,valid token response>> back.


==== Using your platform as SSO

You may want to integrate your existing user base with Boclips. The API will provide a seamless SSO experience.

For your users to be integrated into our platform we will configure upfront an
identity provider (IDP) on our end. At the moment we support SAML 2.0 IDPs and OpenID Connect IDPs.

Once ready, you'll need to perform an https://auth0.com/docs/api-auth/tutorials/authorization-code-grant[authorization code grant flow]
to retrieve an `access_token`

First obtaining a code:

[[trigger-authorization]]
operation::authorization-code-example[snippets='http-request,curl-request']

[[get-token-authorization]]
Then obtaining the `access_token`:

operation::authorization-code-token-example[snippets='http-request,curl-request']

Such a flow will look like this:

. The user's browser visits your application. The application notices the user is not logged in, so it
<<trigger-authorization,redirects the browser to our server>> to be authenticated. The application passes along a callback URL (a redirect URL)
as a query parameter in this browser redirect that our server will use when it finishes authentication.
.. If the user has a session in your domain - we'll move to the next point
.. If the user has no session in your domain we'll send her to your login page (this needs to be configured on our end)

. Given your IDP acknowledge your user, our server authenticates the user and creates a one-time, very short lived, temporary code.
Our server redirects back to the application using the callback URL provided earlier and additionally adds the temporary code as a
query parameter in the callback URL.

. Your application extracts the temporary code and <<get-token-authorization,makes a background REST request>> to our authentication server
to exchange the code for an identity, access and refresh token. Once this temporary code has been used once to
 obtain the tokens, it can never be used again. This prevents potential replay attacks.

[[resources]]
= Resources

[[resources-index]]
== Index

The index provides the entry point into the service. Links can be pulled from here.

[[resources-index-access]]
=== Accessing the index

A `GET` request is used to access the index.

operation::resource-index[snippets='http-request,curl-request,http-response,links']

[[resources-video]]
== Video

The video resource contains metadata about a Boclips video asset. This includes basic metadata as well as
streaming details.

[[resources-video-access]]
=== Accessing a single video

A `GET` request against the `video` link will return an individual video as long as its `id` is interpolated
following the provided template under <<resources-index-access,links>>.

operation::resource-video[snippets='path-parameters,http-request,curl-request,http-response,response-fields,links']


[[resources-video-search]]
=== Video search

A `GET` request against the `search` link will return a collection of videos.
Videos can be filtered using the criteria provided under the <<resources-index-access,templated `search` link>>.

operation::resource-video-search[snippets='request-parameters,http-request,curl-request,http-response,response-fields']



