= Boclips LTI Guide
Boclips Engineering;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:sectlinks:
:toc: left
:toclevels: 4
:stylesheet: styles.css

[[overview]]
= Overview

This is the developer reference guide to Boclips LTI implementation.

LTI is used to authenticate external users within the Boclips application. They don’t need to create accounts or log in, an LTI handshake does it on their behalf, making the experience seamless.

LTI protocol assumes that one web application will be opened from or within another web application. The aforementioned resources are thus plain web pages that display content to users. Whether that page is opened in a separate window or embedded within an iframe element is a matter of design preference.

*The high-level flow is:*

* The LMS authenticates itself and the user against the Tool (eg. Boclips)
* If successful, the Tool will:
** set up a session for the user,
** and redirect them to the requested resource

We support both LTI 1.1 and LTI 1.3. Depending on which version is used, the authentication flow and how the supported features can be accessed is different and explained in more detail in this document.

[[boclips-lti-features]]
== LTI Features supported

=== Displaying a single video

The user is able to display a *single video* playable using our interactive player.

NOTE: Note that the assumption is that IDs of resources are known in advance and as a consumer you embed LTI links them as you choose.


=== Searching and embedding videos
This feature allows users to browse our full video library and select the resources (videos) they want to embed in their lesson.
This is a more flexible way of integrating with Boclips as users are not constrained by the pre-selected resources.

*The feature can be used like:*

[example]
--
. User accesses the Boclips search view inside their LMS
. User is able to search videos by text and filter by metadata (eg. video duration, educational level, subject)
. When an appropriate video is found, the user can select it and initiate the embed flow
. The selected resource is sent back to the LMS
--

[[lti-v1p1]]
== LTI 1.1

In LTI 1.1 world, the two parties interacting with each other are:

* *tool provider* -- a service that has resources than can be accessed (_consumed_) using LTI. This is e.g. Boclips,
* *tool consumer* -- yourself, or any other party that wants to access Boclips content using LTI.

There is plenty of detailed documentation available on LTI (some of it linked below), but in a nutshell the simplest LTI workflow that we support looks like this:


[example]
--
1. _tool consumer_ executes an LTI launch request against the _tool provider_. It's a HTTP POST request with some specific parameters,
2. _tool provider_ verifies the launch request (this is discussed further in following sections),
3. if the launch request is valid, _tool provider_ automatically provisions or retrieves a user account, establishes a HTTP session, sets a cookie and responds with a HTTP redirect to requested resource,
4. _tool consumer_ follows the redirect, passing previously received session cookie along,
5. content is displayed to the end user.
--

[[lti-v1p1-authentication]]
=== Authentication

Launch requests are verified based on a pre-shared set of credentials, *consumer key* and *consumer secret*. These are created by Boclips and exchanged with you before any integration can take place -- they can be thought of as an equivalent of API keys.

An LTI 1.1 handshake works as follows:

[example]
--
1. _tool consumer_ collects all parameters required to execute a Launch Request,
2. then it uses the _secret_ to compute an link:https://oauth.net/core/1.0/[OAuth 1.0 signature] for that request. All POST parameters, HTTP method itself and request URL are included in signature generation,
3. the signature is then attached as another POST parameter and the request is executed,
4. upon receiving the request, _tool provider_ removes the signature parameter, recomputes the signature and verifies the request,
5. if the signature matches and all mandatory parameters are present, the request is deemed valid.
--

The key is passed as a part of a launch request and allows to identify different consumers. The secret should be stored in a secure manner and not be exposed to 3rd parties.

More info can be found in the link:https://www.imsglobal.org/specs/ltiv1p1/implementation-guide[official specification].


[[lti-v1p1-boclips-custom-parameters]]
=== Boclips Custom Parameters

We support additional parameters that allow customizing the LTI experience. They can be passed along all the other launch request parameters.

[cols="2,1,1,5"]
include::{snippets}/lti-v1p1-boclips-parameters/request-parameters.adoc[]

[[lti-v1p1-access-video]]
=== Accessing a single video

Resource endpoint to be used is:
[listing]
--
/v1p1/videos/{videoId}
--

The request has to set `lti_message_type` as `basic-lti-launch-request`.

[[lti-v1p1-search-and-embed]]
=== Search and embed

Resource endpoint to be used is:
[listing]
--
/v1p1/search-and-embed
--

The request has to set `lti_message_type` as `ContentItemSelectionRequest`.


[[lti-v1p1-external-resources]]
=== External Resources for LTI 1.1

Below are a mix of official LTI docs from link:https://www.imsglobal.org/[IMS] and articles written by developers that can prove useful when implementing LTI capabilities.

* link:https://www.imsglobal.org/specs/ltiv1p1/implementation-guide[LTI 1.1 official specification]
* link:https://medium.com/lcom-techblog/simple-lti-tool-consumer-in-html-and-javascript-72ca153d7a83[Simple LTI consumer application]
* link:https://community.brightspace.com/s/article/So-you-want-to-extend-your-LMS-Part-1-LTI-Primer[An LTI 1.1 overview from a developer perspective]
* link:https://ltiapps.net/test/tc.php[Tool for testing LTI 1.1 consumers and providers]

[[lti-v1p3]]
== LTI 1.3

_LTI version 1.3 improves upon version by moving away from the use of OAuth 1.0a-style signing for authentication and towards a new security model, using OpenID Connect, signed JWTs, and OAuth2.0 workflows for authentication._

When using LTI 1.3 the parties interacting with each other are:

* *platform* -- yourself, or any other party that wants to access Boclips content using LTI
* *tool* -- a service that has resources than can be accessed using LTI (e.g. Boclips)

=== Configuring the integration

Before the integration can take place, both parties need to exchange configuration entries with each other.

*Boclips URLs*

[example]
--
* Launch URL: https://lti.boclips.com/search-and-embed
* Login initiation URL: https://lti.boclips.com/v1p3/initiate-login
* Authentication Response URL: https://lti.boclips.com/v1p3/authentication-response
* JWKS URL: https://lti.boclips.com/.well-known/jwks
--

*Information to be shared with Boclips*
[example]
--
* Issuer (iss)
* Authentication endpoint URL
* JWKS URL
* Client ID
--

[[lti-v1p3-authentication]]
=== Authentication

An LTI 1.3 handshake works as follows:

[example]
--
1. _platform_ initiates a login request against _tool_
2. _tool_ executes an OAuth 2 Implicit Flow against _platform_'s IdP
3. end user is redirected to the IdP
4. if the user authenticated successfully, the _platform_ has to assemble an link:https://www.oauth.com/oauth2-servers/openid-connect/id-tokens/[ID Token] with the related LTI claims added to it
5. _tool_ validates the ID Token with LTI claims and redirects the user to the LTI resource requested originally
--

More detail can be found in the official link:https://www.imsglobal.org/spec/security/v1p0/[Authentication Workflow specification].


[[lti-v1p3-claims]]
=== Mandatory LTI claims

Details about the mandatory LTI claims can be found in the link:https://www.imsglobal.org/spec/lti/v1p3#required-message-claims[official documentation].

[[lti-v1p3-access-video]]
==== Accessing a single video

The below claims has to be set as:

* `\https://purl.imsglobal.org/spec/lti/claim/message_type` to be `LtiResourceLinkRequest`
* `\https://purl.imsglobal.org/spec/lti/claim/target_link_uri` to be `\https://lti.boclips.com/videos/{videoId}`

[[lti-v1p3-search-and-embed]]
==== Search and embed

The below claims has to be set as:

* `\https://purl.imsglobal.org/spec/lti/claim/message_type` to be `LtiDeepLinkingRequest`
* `\https://purl.imsglobal.org/spec/lti/claim/target_link_uri` to be `\https://lti.boclips.com/search-and-embed`

[[lti-v1p3-external-resources]]
=== External Resources

* link:https://www.imsglobal.org/spec/lti/v1p3[LTI 1.3 official specification]
* link:https://www.imsglobal.org/spec/security/v1p0/[LTI 1.3 Authentication Workflow specification]
* link:http://www.imsglobal.org/spec/lti-dl/v2p0/[LTI Deep Linking Specification]

