[[overview-hypermedia]]
== Hypermedia

The API uses hypermedia, and resources include links to other resources in their
responses. Responses are in http://stateless.co/hal_specification.html[Hypertext Application
from resource to resource Language (HAL)] format. Links can be found beneath the `_links` key of retrieved resource.

Note that one of the goals of indirection introduced through hypermedia and links is to handle API changes. *Users of the API should not use hardcoded resource URIs*, but instead use the above-described links to navigate the API. This way they'll always receive correct and up-to-date URIs to resources they need.

More information on _Hypermedia as the Engine of Application State_ (HATEOAS) can be found https://en.wikipedia.org/wiki/HATEOAS[here].

[[overview-interpolating-urls]]
=== Interpolating URLs

As part of the HAL links spec, the API may return templated URLs. In order to obtain the effective URL, you will need to interpolate
values appropriately.

If a link is templated, its `templated` property will be set to true, for example:

[source,json]
----
{
  "_links": {
    "video": {
      "href": "https://api.boclips.com/v1/videos/{id}",
      "templated": true
    }
  }
}
----

Now if you wanted to use that link, you need to interpolate the value of `id` with the identifier corresponding to your video. If you are implementing a web application, libraries such as https://medialize.github.io/URI.js/uri-template.html[URI.js]
will take care of this for you. Most major web frameworks should support this pattern.

Please keep in mind, some params may be mandatory, whereas others may be optional. Also, although logical names for
params will remain consistent to avoid breaking changes, mandatory params may become optional or vice-versa.

For instance you may get a URL that looks like:
`https://api.boclips.com/v1/resource/{resourceId}?mandatoryParam1={mandatoryParam1}&mandatoryParam2={mandatoryParam2}{&optionalParam}`

Which over time could become:
`https://api.boclips.com/v1/resource/{resourceId}?mandatoryParam={mandatoryParam}{&mandatoryParam2,optionalParam}`

This sort of modifications should not break your client.
