[[faq]]
= Frequently asked questions
:version-label: API Version
:doctype: book
:icons: font
:source-highlighter: highlightjs
:sectlinks:
:favicon:
:hide-uri-scheme:


[[credentials]]
=== How can we get the credentials?
Visit http://boclips.com/integrate, click *Start for Free*, and fill out the form. You'll receive your API key in 2-3 business days. Please allow up to 5 business days around US and UK Holidays.
[[authenticate]]
=== How can my service authenticate?
Your service needs to obtain an access token and use it in the following API calls - link:/docs/getting-started-api/authenticating.html[this] page describes how to do it

[[cors]]
=== I am getting CORS exceptions - what can I do?
In order to make your CORS issues go away, we will need to whitelist the various domains you’ll be making calls from. Please reach out to your account manager to get it done; alternatively contact support@boclips.com

[[streaming-links]]
=== How long are video streaming links valid?
Each video resource contains an HLS link that is used for streaming. Such link has a lifespan of 48 hours, beyond this the video will need to be retrieved again. More on fetching videos can be found link:/docs/api-guide/index.html#resources-video-access[here]

[[whitelabeled-experience]]
=== Can this API integration be a white-labeled experience?
Yes! All API integrations can be created to be completely native to your platform.

[[integration-support]]
=== What should I do if I face any other issues?
Please reach out to your account manager if you face any difficulties; alternatively, contact support@boclips.com
