#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
cat > "$cwd/application-test.yml" <<EOF
api.username: api@boclips.com
api.password: "$(bo show credential concourse-main boclips.api-docs api-user-password)"
api.clientid: api-docs
api.clientsecret: $(bo show credential concourse-main keycloak-vars staging | jq .api_docs_client_secret)
api.freshuser.username: fresh@user.com
api.freshuser.password: $(bo show credential concourse-main boclips.api-docs fresh-user-password)
api.updatableuser.username: updatable@user.com
api.updatableuser.password: $(bo show credential concourse-main boclips.api-docs updatable-user-password)
api.productionuser.username: engineering+api-docs@boclips.com
api.productionuser.password: $(bo show credential concourse-main boclips.api-docs production-user-password)
lti.v1p1.consumerkey: api-docs
lti.v1p1.consumersecret: $(bo show credential concourse-main boclips.api-docs lti-v1p1-consumer-secret)
EOF
