apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
namespace: production
replicas:
- count: 2
  name: api-docs
patches:
- path: domain.yaml
  target:
    group: extensions
    kind: Ingress
    version: v1beta1
- path: jaeger-service-name.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
