- op: replace
  path: /spec/template/spec/containers/0/readinessProbe
  value:
    successThreshold: 1
    failureThreshold: 6
    timeoutSeconds: 5
    initialDelaySeconds: 20
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 10
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    successThreshold: 1
    failureThreshold: 2
    timeoutSeconds: 5
    initialDelaySeconds: 80
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 10
